-- Up Migration
CREATE TABLE "user" (
  "id" UUID PRIMARY KEY DEFAULT (gen_random_uuid()),
  "created_at" timestamp NOT NULL DEFAULT (now()),
  "email" varchar UNIQUE NOT NULL,
  "market" varchar NOT NULL,
  "password" varchar NOT NULL,
  "spotify_id" varchar UNIQUE NOT NULL
);

CREATE TABLE "playlist" (
  "id" UUID PRIMARY KEY DEFAULT (gen_random_uuid()),
  "created_at" timestamp NOT NULL DEFAULT (now()),
  "created_by" UUID,
  "last_updated" timestamp,
  "last_updated_by" UUID,
  "spotify_id" varchar
);

CREATE TABLE "playlist_editor" (
  "editor_id" UUID,
  "playlist_id" UUID,
  PRIMARY KEY ("playlist_id", "editor_id")
);

CREATE TABLE "slot" (
  "id" UUID PRIMARY KEY DEFAULT (gen_random_uuid()),
  "created_at" timestamp NOT NULL DEFAULT (now()),
  "last_updated" timestamp,
  "name" varchar NOT NULL,
  "playlist_id" UUID NOT NULL,
  "pool_id" UUID,
  "type" integer
);

CREATE TABLE "slot_type" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar
);

CREATE TABLE "pool" (
  "id" UUID PRIMARY KEY DEFAULT (gen_random_uuid()),
  "last_updated" timestamp,
  "spotify_id" varchar
);

CREATE TABLE "pool_track" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "pool_id" UUID NOT NULL,
  "spotify_track_id" varchar,
  "spotify_artist_id" varchar
);

COMMENT ON COLUMN "pool_track"."spotify_artist_id" IS 'not currently needed. for future feature banning tracks/artists';

ALTER TABLE "playlist" ADD FOREIGN KEY ("created_by") REFERENCES "user" ("id");

ALTER TABLE "playlist" ADD FOREIGN KEY ("last_updated_by") REFERENCES "user" ("id");

ALTER TABLE "playlist_editor" ADD FOREIGN KEY ("editor_id") REFERENCES "user" ("id");

ALTER TABLE "playlist_editor" ADD FOREIGN KEY ("playlist_id") REFERENCES "playlist" ("id");

ALTER TABLE "slot" ADD FOREIGN KEY ("playlist_id") REFERENCES "playlist" ("id");

ALTER TABLE "slot" ADD FOREIGN KEY ("pool_id") REFERENCES "pool" ("id");

ALTER TABLE "slot" ADD FOREIGN KEY ("type") REFERENCES "slot_type" ("id");

ALTER TABLE "pool_track" ADD FOREIGN KEY ("pool_id") REFERENCES "pool" ("id");

-- Down Migration
DROP TABLE user;
DROP TABLE playlist;
DROP TABLE playlist_editor;
DROP TABLE slot;
DROP TABLE slot_type;
DROP TABLE 'pool';
DROP TABLE pool_track;